In [1]:
# importing numpy 
import numpy

In [2]:
# print version of numpy
print(numpy.__version__)

1.23.5


In [3]:
# use alias to import numpy
import numpy as np

In [4]:
# print the version of numpy using alias
print(np.__version__)

1.23.5


In [5]:
# creating a 0 Dimension numpy array using single number
x = np.array(2)

In [6]:
# print the 0-D numpy array
print(x)

2


In [7]:
# check the dimension of array
print(x.ndim)

0


In [8]:
# cerate a 1-D array
y = np.array([1,2,3])
# print this 1-D array
print(y)
# check the dimesnsion of numpy array y
print(y.ndim)

[1 2 3]
1


In [10]:
# create a 2-D array
z = np.array([[1,2,3],[4,5,6]])
# print this 2-D array
print(z)
# check the dimension of numpy array z
print(z.ndim)

[[1 2 3]
 [4 5 6]]
2


In [11]:
# create a 3-D array
k = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
# print this 3-D array
print(k)
# check the dimension of numpy array k
print(k.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [12]:
# usage of ndmin argument for create higher dimension numpy array
m = np.array([1,2,3,4], ndmin = 4)
# print this numpy array
print(m)
# verify the dimension of this numpy array
print(m.ndim)

[[[[1 2 3 4]]]]
4


In [13]:
# accessing the elements of 1-D array
# print the first element
# here y is 1D array storing [1,2,3]
print(y[0])
# print the second element
print(y[1])

1
2


In [14]:
# use negative indexing for accessing the elements of 1-D array
# print the last element
print(y[-1])
# print the 2nd element from the end
print(y[-2])

3
2


In [19]:
# print the last 2 elements of y using negative indexing
print(y[-2:])

[2 3]


In [20]:
# accessing elements of a 2-D numpy array
# use numpy array z = [[1,2,3],[4,5,6]]
# to print 2 use row 0 and column 1
print(z[0,1])

2


In [21]:
# using negative indexing for accessing a 2-D array
# use row 0 and column -1 to print 3 as output
print(z[0,-1])

3


In [22]:
# accessing elements of a 3-D numpy array
# use numpy array k which currently has value [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
# to print 4 use the index combination of 0,1,0
print(k[0,1,0])

4


In [23]:
# slicing a numpy array
# create a numpy array
x = np.array([1,2,3,4,5,6,7,8,9])

In [24]:
# print elements from index position 1 to 4
print(x[1:5])

[2 3 4 5]


In [25]:
# print elements from index position 1 to end
print(x[1:])

[2 3 4 5 6 7 8 9]


In [26]:
# print elements from index position 1 to 7 with step size of 2
print(x[1:8:2])

[2 4 6 8]


In [32]:
# slicing a 2-D numpy array
# use z which is currently storing [[1,2,3],[4,5,6]]
# the following line will print [5] as ouput
print(z[1, 1:2])

[5]


In [42]:
# create another 2-D numpy array
arr1 = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
# the following statement will print [[3,4,5,6],[10,11,12,13]] as output
print(arr1[0:2, 2:6])

[[ 3  4  5  6]
 [10 11 12 13]]


In [35]:
# use of property dtype
print(arr1.dtype)

int32


In [37]:
# dtype can be used when you define numpy array
arr2 = np.array([1,2,3,4,5,6,7], dtype='S')
print(arr2.dtype)

|S1


In [39]:
# use of astype
arr3 = np.array([1.1, 2.2, 3.3, 4.4, 5.5])
arr4 = arr3.astype('i')
print(arr4.dtype)
print(arr4)

int32
[1 2 3 4 5]


In [43]:
# copy vs view
arr5 = arr1.copy()
arr1[0,0] = 15
print(arr1)
print('---------')
print(arr5)

[[15  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
---------
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [44]:
# now lets use view
# first redefine arr1
arr1 = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
arr5 = arr1.view()
arr1[0,0] = 15
print(arr1)
print('-------')
print(arr5)

[[15  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
-------
[[15  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [45]:
# use of base
# None is retuuned in case numpy array owns the data otherwise original object is returned
print(arr1.base)
print(arr5.base)

None
[[15  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [46]:
#  use of shape 
# it returns a tuple with each index showing the number of corresponding elements 
print(arr1.shape)

(2, 7)


In [47]:
# use of reshape
# used to change the numpy array dimesnion
#  for example from 1-D to 2-D, from 1-D to 3-D
# reshaping is possible provided the number of elements in the reshaped array are same as that in the original array
# create a 1-D numpy array
arr6 = np.array([1,2,3,4,5,6,7,8,9])
print(arr6)
print(arr6.shape)
print('------------')
arr7 = arr6.reshape(3,3)
print(arr7)

[1 2 3 4 5 6 7 8 9]
(9,)
------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
# reshape 1-D numpy array to 3-D numpy array
arr8 = np.array([1,2,3,4,5,6,7,8])
arr9 = arr8.reshape(2,2,2)
print(arr9)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
