In [1]:
# use of zeros and ones to create a numpy array of 0s and 1s
import numpy as np
x = np.zeros(3)
print(x)

[0. 0. 0.]


In [2]:
# 2D array of zeros 
y = np.zeros((3,3))
print(y)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
# 1 D array of ones
print(np.ones(3))

[1. 1. 1.]


In [4]:
# 2d array of ones
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
#  use of line space
# used for generating evenly spaced numbers
# for example use the following for generating 3 evenly spaced numbers between 0 to 20
print(np.linspace(0,20,3))

[ 0. 10. 20.]


In [6]:
# generate 50 evenly spaced numbers between 0 to 20
print(np.linspace(0,20,50))

[ 0.          0.40816327  0.81632653  1.2244898   1.63265306  2.04081633
  2.44897959  2.85714286  3.26530612  3.67346939  4.08163265  4.48979592
  4.89795918  5.30612245  5.71428571  6.12244898  6.53061224  6.93877551
  7.34693878  7.75510204  8.16326531  8.57142857  8.97959184  9.3877551
  9.79591837 10.20408163 10.6122449  11.02040816 11.42857143 11.83673469
 12.24489796 12.65306122 13.06122449 13.46938776 13.87755102 14.28571429
 14.69387755 15.10204082 15.51020408 15.91836735 16.32653061 16.73469388
 17.14285714 17.55102041 17.95918367 18.36734694 18.7755102  19.18367347
 19.59183673 20.        ]


In [7]:
#  use of eye function to create idenntity matrix
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
# use random module of numpy
import random
# returns a single random value between 1 and 30
print(np.random.randint(1,30))

27


In [9]:
# returns 3 random values between 1 and 30
print(np.random.randint(1,30,3))

[ 4 13 29]


In [10]:
# generate 2d array containing 2 rows and each row containing 2 elements
print(np.random.rand(2,2))

[[0.55263672 0.16074884]
 [0.31876112 0.55648888]]


In [11]:
# use randn for generating numpy array of random numbers using normal distrib
print(np.random.randn(2))

[-1.63568127  0.21633867]


In [12]:
# use choice function to generate numpy array
print(np.random.choice([1,2,3,4,5,6],size=(3,3)))

[[3 5 5]
 [6 4 3]
 [4 6 3]]


In [13]:
# max and min from numpy array and its index position
# make a 1-D numpy array
arr = np.array([1,2,3,4,5,6,7,8,9])
# get the maximum value of a numpy array
print(arr.max())
# get the index position of the maximum value of numpy array
print(arr.argmax())
# get the minimum value of a numpy array
print(arr.min())
# get the index position of the minimum value of numpy array
print(arr.argmin())

9
8
1
0


In [14]:
import numpy as np
# search a numpy array
p = np.array([1,2,3,4,5,6])
# print index where element 5 exists
print(np.where(p==5))

(array([4], dtype=int64),)


In [15]:
# sort the array
p = np.array([7,5,8,6,9,1])
q = np.sort(p)
print(p)
print('-------')
print(q)

[7 5 8 6 9 1]
-------
[1 5 6 7 8 9]


In [16]:
# find square root of values of numpy array
p = np.array([4,9,16,25])
q = np.sqrt(p)
print(q)

[2. 3. 4. 5.]


In [17]:
# filter the data by traversing through numpy array
# take data values that are greater than 6 in another array
p = np.array([4,6,2,7,9])
q = []
for i in p:
    if i>6:
        q.append(i)
print(q)

[7, 9]


In [18]:
# split the numpy array
p = np.array([1,2,3,4,5,6])
q = np.split(p,2)
print(q)

[array([1, 2, 3]), array([4, 5, 6])]


In [19]:
# split a 2-D array
p = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
q = np.split(p,2)
print(q)
print(q[0])
print(q[1])

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [29]:
# concatenating numpy array
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.concatenate((arr1,arr2))
print(arr3)
arr4 = np.vstack((arr1,arr2))
print('-------------')
print(arr4)
arr5 = np.dstack((arr1,arr2))
print('-------------')
print(arr5)

[1 2 3 4 5 6]
-------------
[[1 2 3]
 [4 5 6]]
-------------
[[[1 4]
  [2 5]
  [3 6]]]


In [25]:
# concatenating a 2-D numpy array
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr3 = np.concatenate((arr1,arr2))
print(arr3)
arr4 = np.concatenate((arr1,arr2), axis=1)
print('-----------')
print(arr4)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
-----------
[[1 2 5 6]
 [3 4 7 8]]


In [30]:
# iterating a numpy array
# for 1-D array
arr1 = np.array([1,2,3,4,5])
for i in arr1:
    print(i)

1
2
3
4
5


In [31]:
# iterate a 2-D array
arr2 = np.array([[1,2,3],[4,5,6]])
for i in arr2:
    for j in i:
        print(j)

1
2
3
4
5
6


In [33]:
# iterate a 3-D array
arr3 = np.array([[[1,2,3],[4,5,6]], [[6,7,5],[9,4,2]]])
for i in arr3:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
6
7
5
9
4
2


In [35]:
# some more operations
arr1 = np.array([1,2,3,4,5,6,7,8,9])
# print sum of all the elements of numpy array
print(arr1.sum())
# print standard deviation
print(arr1.std())

45
2.581988897471611


In [36]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr2.sum(axis=0))
# this prints the sum of all the columns in numpy array

[22 26 30]
